import { StyleSheet } from 'react-native';
import colors from './colors';
import { fonts } from './fonts';

const globalStyles = StyleSheet.create({
  addButton: {
    alignSelf: 'flex-start',
    backgroundColor: colors.yellow,
    borderRadius: 6,
    paddingHorizontal: 14,
    paddingVertical: 6,
    top: 50
  },
  addExerciseButton: {
    backgroundColor: colors.yellow,
    borderRadius: 30,
    bottom: 70,
    elevation: 5,
    paddingHorizontal: 16,
    paddingVertical: 10,
    position: 'absolute',
    right: 20,
  },
  backButton: {
    left: 20,
    padding: 10,
    position: "absolute",
    top: 50,
    zIndex: 1,
  },
  backButtonText: {
    color: '#555',
    fontSize: 16,
  },
  bemVindo: {
    color: colors.black,
    fontFamily: fonts.michroma,
    fontSize: 30,
    padding: 30,
    right: 15,
    top: 15
  },
  button: {
    alignItems: "center",
    margin: 8,
  },
  buttonLoginTeacher: {
    alignItems: 'center',
    borderColor: colors.black,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 15,
    padding: 15,
  },
  buttonLoginUser: {
    alignItems: "center",
    paddingTop: 25,
  },
  buttonOnBoarding: {
    alignItems: 'center',
    backgroundColor: colors.darkGray,
    borderColor: colors.lightGray,
    borderRadius: 30,
    borderWidth: 1,
    elevation: 5,
    fontFamily: fonts.roboto700B,
    justifyContent: "center",
    marginVertical: 5,
    padding: 15,
  },
  buttonRegisterUser: {
    alignItems: 'center',
    backgroundColor: colors.darkGray,
    borderColor: colors.lightGray,
    borderRadius: 30,
    borderWidth: 1,
    color: colors.lightGray,
    elevation: 5,
    fontSize: 20,
    fontWeight: 'bold',
    marginTop: 5,
    padding: 15,
  },
  buttonShowVideo: {
    alignItems: "center",
    backgroundColor: colors.yellow,
    borderColor: colors.black,
    borderRadius: 8,
    borderWidth: 1.5,
    bottom: 25,
    justifyContent: "center",
    left: 10,
    width: 110
  },
  buttonShowVideoProfile: {
    alignItems: "center",
    backgroundColor: colors.yellow,
    borderColor: colors.black,
    borderRadius: 8,
    borderWidth: 1.5,
    justifyContent: "center",
    left: 10,
    top: 3,
    width: 110
  },
  buttonText: {
    color: colors.lightGray,
    fontSize: 20,
    fontWeight: 'bold',
  },
  cancelButton: {
    alignItems: 'center',
    backgroundColor: colors.darkGray,
    borderRadius: 8,
    padding: 14,
    top: 5
  },
  cancelButtonText: {
    color: colors.white,
    fontFamily: fonts.roboto700B,
  },
  card: {
    alignSelf: "center",
    backgroundColor: "#555555ff",
    borderColor: colors.black,
    borderRadius: 15,
    borderWidth: 2,
    elevation: 5,
    height: 165,
    margin: 5,
    width: 370,
  },
  cardHomeTeacher: {
    alignContent: "center",
    backgroundColor: "#555555ff",
    borderColor: colors.black,
    borderRadius: 10,
    borderWidth: 2,
    justifyContent: "center",
    left: 20,
    marginBottom: 10,
    padding: 15,
    top: 70,
    width: "90%",
  },
  circleCheck: {
    alignItems: 'center',
    borderColor: colors.black,
    borderRadius: 11,
    borderWidth: 2,
    height: 22,
    justifyContent: 'center',
    marginRight: 10,
    width: 22,
  },
  contact: {
    color: colors.yellow,
    fontSize: 20,
    right: 60,
    textDecorationLine: 'underline',
    top: 26,
  },
  container: {
    backgroundColor: colors.yellow,
    flex: 1,
    justifyContent: "center",
    padding: 30,
  },
  containerCardsProfileId: {
    backgroundColor: colors.darkGray,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    top: 30,
  },
  containerCardsTeacher: {
    backgroundColor: colors.darkGray,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    flex: 1,
    justifyContent: "center",
    top: 10,
  },
  containerHomeTeacher: {
    backgroundColor: colors.yellow,
    flex: 1,
  },
  containerHomeUser: {
    backgroundColor: colors.yellow,
    flex: 1,
    bottom: 10
  },
  containerProfileId: {
    backgroundColor: colors.yellow,
    flex: 1,
  },
  containerProfileUser: {
    backgroundColor: colors.darkGray,
    borderRadius: 20,
    flex: 1,
    justifyContent: "center",
    top: 80,
  },
  containerStyle: {
    backgroundColor: colors.darkGray,
    paddingBottom: 16,
    paddingTop: 20,
  },
  dayLabel: {
    fontSize: 20,
    fontWeight: 'bold',
    marginVertical: 10,
  },
  deleteButtonText: {
    color: 'red',
    marginTop: 8,
  },
  disabledButton: {
    opacity: 0.5,
  },
  emptyButton: {
    alignItems: 'center',
    borderRadius: 8,
    marginVertical: 5,
    padding: 15,
  },
  emptyButtonText: {
    alignItems: 'center',
    borderColor: colors.black,
    fontSize: 18,
    left: 50,
    top: 10
  },
  errorText: {
    color: 'red',
    marginBottom: 8,
  },
  exerciseInput: {
    flex: 1,
    marginRight: 8,
  },
  exerciseInputContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 12,
  },
  exerciseItem: {
    alignItems: 'center',
    backgroundColor: '#fff',
    borderColor: colors.black,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
    padding: 12,
  },
  homeUser: {
    backgroundColor: colors.darkGray,
    flex: 1,
  },
  input: {
    backgroundColor: colors.lightGray,
    borderColor: "#9b9b9bff",
    borderRadius: 30,
    borderWidth: 1,
    height: 50,
    marginVertical: 4,
    padding: 10,
  },
  label: {
    color: colors.black,
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
    marginTop: 12,
  },
  line: {
    alignSelf: "center",
    color: colors.lightGray,
    fontSize: 24,
    position: 'absolute',
    textShadowColor: colors.black,
    textShadowOffset: { width: -2, height: 2 },
    textShadowRadius: 1,
    top: 55,
  },
  lineBetweenCards: {
    alignSelf: "center",
    backgroundColor: colors.yellow,
    elevation: 3,
    height: 2,
    position: 'absolute',
    shadowColor: colors.white,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
    top: 125,
    width: "40%",
  },
  loadingContainer: {
    alignItems: 'center',
    backgroundColor: colors.darkGray,
    flex: 1,
    justifyContent: 'center',
  },
  logoutTeacher: {
    color: colors.red,
    fontFamily: fonts.robotoRegular,
    fontSize: 20,
    right: 25,
    top: 10,
  },
  logoutUser: {
    alignSelf: "center",
    color: colors.red,
    fontSize: 20,
    right: 40,
    top: 26,
  },
  menuTeacher: {
    backgroundColor: colors.darkGray,
    borderColor: colors.black,
    borderRadius: 8,
    borderWidth: 1.5,
    elevation: 5,
    height: 70,
    padding: 10,
    position: 'absolute',
    right: 0,
    shadowColor: colors.lightGray,
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 4,
    top: 110,
    width: 90,
    zIndex: 20,
  },
  menuUser:{
    position: 'absolute',
    top: 100,
    right: 0,
    width: '40%',
    height: '15%',
    backgroundColor: colors.darkGray,
    zIndex: 10,
    paddingTop: 80,
    paddingHorizontal: 20,
    shadowColor: colors.lightGray,
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 1,
    elevation: 5,
    borderRadius: 8,
    borderColor: colors.black,
    borderWidth: 2,
  },
  modalContainer: {
    backgroundColor: colors.black,
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  removeButtonExercise: {
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: colors.red,
    borderColor: colors.black,
    borderRadius: 8,
    borderWidth: 1,
    bottom: 28,
    elevation: 3,
    justifyContent: 'center',
    padding: 5,
    right: 8,
  },
  removeStudentButton: {
    alignItems: 'center',
    alignSelf: "center",
    backgroundColor: colors.red,
    borderColor: colors.black,
    borderRadius: 8,
    borderWidth: 1,
    elevation: 3,
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    right: 130,
    top: 10,
  },
  removeStudentButtonText: {
    color: colors.lightGray,
    fontFamily: fonts.roboto700B,
    fontSize: 14,
    justifyContent: "center"
  },
  rest: {
    bottom: 18,
    color: colors.red,
    fontFamily: fonts.roboto700B,
    fontSize: 17,
    left: 13,
    textDecorationLine: "underline",
  },
  saveButton: {
    alignItems: 'center',
    backgroundColor: colors.yellow,
    borderRadius: 8,
    marginVertical: 5,
    padding: 14,
    top: 5,
  },
  saveButtonText: {
    color: colors.black,
    fontFamily: fonts.roboto700B,
  },
  scrollContent: {
    backgroundColor: colors.yellow,
    flexGrow: 1,
    justifyContent: 'center',
    padding: 20,
  },
  sectionTitle: {
    alignItems: "center",
    alignSelf: "center",
    bottom: 30,
    color: colors.yellow,
    fontFamily: fonts.merienda,
    fontSize: 20,
    justifyContent: "center",
  },
  submitButton: {
    alignItems: 'center',
    backgroundColor: colors.yellow,
    borderRadius: 10,
    marginTop: 20,
    paddingHorizontal: 24,
    paddingVertical: 14,
  },
  submitButtonText: {
    color: colors.black,
    fontSize: 16,
    fontWeight: 'bold',
  },
  subtitle: {
    color: colors.lightGray,
    fontSize: 25,
    justifyContent: "center",
    marginBottom: 30,
    textAlign: "center",
    textShadowColor: colors.black,
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 10,
  },
  text: {
    alignItems: "center",
    fontSize: 15,
    justifyContent: "center",
    left: 70,
    textDecorationLine: "underline"
  },
  textButton: {
    fontSize: 15,
    textDecorationLine: "underline",
    top: 5,
  },
  textButtonCad: {
    color: colors.black,
    fontSize: 15,
    alignSelf: 'center',
    textDecorationLine: "underline",
    top: 20,
  },
  textEmail: {
    color: colors.lightGray,
    fontSize: 14,
  },
  textHomeTeacher: {
    alignSelf: "center",
    color: colors.yellow,
    fontFamily: fonts.merienda,
    fontSize: 30,
    justifyContent: "center",
    textShadowColor: colors.black,
    textShadowOffset: { width: -1, height: 3 },
    textShadowRadius: 1,
    top: 25,
  },
  textHomeUser: {
    color: colors.yellow,
    fontFamily: fonts.merienda,
    fontSize: 25,
    justifyContent: "center",
    margin: 5,
    padding: 5,
    textAlign: "center",
    textShadowColor: colors.black,
    textShadowOffset: { width: -2, height: 2 },
    textShadowRadius: 5,
  },
  textNameExercise: {
    alignSelf: "center",
    bottom: 15,
    color: colors.lightGray,
    fontFamily: fonts.merienda,
    fontSize: 20,
    justifyContent: "center",
    textAlign: "center",
    textDecorationLine: "underline",
  },
  textNameExerciseId: {
    alignSelf: "center",
    color: colors.lightGray,
    fontFamily: fonts.roboto700B,
    fontSize: 20,
    justifyContent: "center",
    textAlign: "center",
    textDecorationLine: 'underline',
    top: 8,
  },
  textNameHomeTeacher: {
    color: colors.lightGray,
    fontSize: 18,
    fontWeight: '500',
  },
  textProfileId: {
    color: colors.yellow,
    fontSize: 30,
    fontWeight: "bold",
    justifyContent: "center",
    margin: 10,
    paddingTop: 5,
    textAlign: "center",
  },
  textRestExercise: {
    alignItems: "center",
    bottom: 40,
    color: colors.lightGray,
    fontFamily: fonts.robotoRegular,
    fontSize: 15,
    justifyContent: "center",
    left: 100,
  },
  textRestExerciseId: {
    alignItems: "center",
    color: colors.lightGray,
    fontFamily: fonts.robotoRegular,
    fontSize: 15,
    justifyContent: "center",
    left: 100,
    top: 8,
  },
  textShowVideo: {
    alignItems: "center",
    color: colors.black,
    fontSize: 15,
    fontWeight: 'bold',
    justifyContent: "center",
    padding: 5,
  },
  textShowVideoProfile: {
    alignItems: "center",
    color: colors.black,
    fontSize: 15,
    fontWeight: "bold",
    justifyContent: "center",
    padding: 5,
  },
  textVolumeExercise: {
    alignItems: "center",
    bottom: 25,
    color: colors.lightGray,
    fontFamily: fonts.robotoRegular,
    fontSize: 15,
    justifyContent: "center",
    left: 85,
  },
  textVolumeExerciseId: {
    alignItems: "center",
    color: colors.lightGray,
    fontFamily: fonts.robotoRegular,
    fontSize: 15,
    justifyContent: "center",
    left: 85,
    top: 23,
  },
  title: {
    fontFamily: "Michroma_400Regular",
    fontSize: 60,
    justifyContent: "center",
    marginBottom: 25,
    textAlign: "center",
  },
  titleHomeTeacher: {
    fontSize: 30,
    fontWeight: 'bold',
    left: 15,
    top: 50,
  },
  titleProfileId: {
    alignItems: "center",
    color: colors.black,
    fontFamily: fonts.michroma,
    fontSize: 25,
    justifyContent: "center",
    left: 60,
    top: 55,
  },
  video: {
    backgroundColor: '#000',
    borderRadius: 10,
    height: 200,
    width: '100%',
  },
  viewHomeUser: {
    backgroundColor: colors.darkGray,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    bottom: 10
  },
  viewProfileId: {
    backgroundColor: colors.darkGray,
    paddingBottom: 5,
    paddingHorizontal: 20,
    paddingTop: 5,
  },
  volume: {
    bottom: 4,
    color: colors.green,
    fontFamily: fonts.roboto700B,
    fontSize: 17,
    left: 13,
    textDecorationLine: "underline",
  },
});

export default globalStyles;
